apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcf-light-bot.fullname" . }}-server
  namespace: {{ include "dcf-light-bot.namespace" . }}
  labels:
    {{- include "dcf-light-bot.serverLabels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "dcf-light-bot.serverSelector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcf-light-bot.fullname" . }}-client
  namespace: {{ include "dcf-light-bot.namespace" . }}
  labels:
    {{- include "dcf-light-bot.clientLabels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  selector:
    {{- include "dcf-light-bot.clientSelector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
