apiVersion: v1
kind: Service
metadata:
  name: dcf-server
  namespace: dcf-system
  labels:
    app.kubernetes.io/name: dcf-light-bot
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dcf-light-bot
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 3002
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: dcf-client
  namespace: dcf-system
  labels:
    app.kubernetes.io/name: dcf-light-bot
    app.kubernetes.io/component: client
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dcf-light-bot
    app.kubernetes.io/component: client
  ports:
    - name: http
      port: 80
      targetPort: http
